<?php


namespace app\components;


use app\models\Comment;
use yii\base\Widget;

class CommentWidget extends Widget
{
    public $tpl;
    public $ul_class;
    public $data;
    public $tree;
    public $menuHtml;
    public $id;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->ul_class = '';

    }

    public function run()
    {

        $this->data = Comment::find()->indexBy('id')->with('user')->where(['post_id' => $this->id])->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHtml = '<ul class=" ' . $this->ul_class . ' ">';
        $this->menuHtml .= $this->getMenuHtml($this->tree);
        $this->menuHtml .= '</ul>';


        return $this->menuHtml;
    }

    public function getTree()
    {
        $tree = [];
        foreach ($this->data as $id => &$node) {
            if (!$node['parent_id']) {
                $tree[$id] =& $node;
            } else {
                $this->data[$node['parent_id']]['children'][$node['id']] =& $node;
            }

        }
        return $tree;
    }

    protected function getMenuHtml($tree, $tab = '')
    {

        $str = '';
        foreach ($tree as $comment) {
            $str .= $this->catToTemplate($comment, $tab);
        }
        return $str;
    }

    protected function catToTemplate($comment, $tab)
    {
        ob_start();
        include __DIR__ . '/views/comment.php';
        return ob_get_clean();
    }
}